"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _homepage from './homepage.bones.json'
import _products_page from './products-page.bones.json'
import _about_page from './about-page.bones.json'
import _contact_page from './contact-page.bones.json'
import _cart_page from './cart-page.bones.json'
import _login_page from './login-page.bones.json'
import _help_page from './help-page.bones.json'
import _product_detail from './product-detail.bones.json'
import _team_page from './team-page.bones.json'
import _careers_page from './careers-page.bones.json'
import _press_page from './press-page.bones.json'
import _privacy_page from './privacy-page.bones.json'
import _terms_page from './terms-page.bones.json'

configureBoneyard({"color":"#e5e5e5","animate":"pulse"})

registerBones({
  "homepage": _homepage,
  "products-page": _products_page,
  "about-page": _about_page,
  "contact-page": _contact_page,
  "cart-page": _cart_page,
  "login-page": _login_page,
  "help-page": _help_page,
  "product-detail": _product_detail,
  "team-page": _team_page,
  "careers-page": _careers_page,
  "press-page": _press_page,
  "privacy-page": _privacy_page,
  "terms-page": _terms_page,
})
